### ISSUE TITLE
krita 5.2.0: NameError: name 'HSL' is not defined

### ISSUE THREAD

**Issue by Gnumaru** [EyeOdin/Pigment.O#20]
When launching on windows the latest version of krita (5.2) with the latest version of Pigment.O (master branch, commit bef7d8e7a1ac82401582003ce837879d1ff65d7c ) I get the error "NameError: name 'HSL' is not defined"

```
NameError
Python 3.10.7: C:\opt\Kritax64\bin\krita.exe
Wed Oct 11 12:06:25 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\opt\Kritax64\lib\krita-python-libs\krita\dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'pigment_o.pigment_o_docker.PigmentO_Docker'>

 C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in __init__(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>)
   87         self.Timer()
   88         self.Extension()
   89         self.Settings()
   90         self.Loader()
   91 
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Settings = <bound method PigmentO_Docker.Settings of <pigment_o.pigment_o_docker.PigmentO_Docker object>>

 C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Settings(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>)
 1572 
 1573         # Colors
 1574         self.Dict_Copy( har_01, self.Set_Read( "EVAL", "har_01", har_01 ) )
 1575         self.Dict_Copy( har_02, self.Set_Read( "EVAL", "har_02", har_02 ) )
 1576         self.Dict_Copy( har_03, self.Set_Read( "EVAL", "har_03", har_03 ) )
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Dict_Copy = <bound method PigmentO_Docker.Dict_Copy of <pigment_o.pigment_o_docker.PigmentO_Docker object>>
global har_01 = {'aaa_1': 0, 'aaa_d1': 0, 'active': False, 'ard_1': 0, 'ard_2': 0, 'ard_3': 0, 'cmy_1': 0, 'cmy_2': 0, 'cmy_3': 0, 'cmyk_1': 0, ...}
self.Set_Read = <bound method PigmentO_Docker.Set_Read of <pigment_o.pigment_o_docker.PigmentO_Docker object>>

 C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Set_Read(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>, mode='EVAL', entry='har_01', default={'aaa_1': 0, 'aaa_d1': 0, 'active': False, 'ard_1': 0, 'ard_2': 0, 'ard_3': 0, 'cmy_1': 0, 'cmy_2': 0, 'cmy_3': 0, 'cmyk_1': 0, ...})
 1782             read = setting
 1783             if mode == "EVAL":
 1784                 read = eval( read )
 1785             elif mode == "STR":
 1786                 read = str( read )
read = 'HSL,0,0,0,0,0,0'
builtineval = <built-in function eval>

 C:\opt\Kritax64\<string> in <module>

NameError: name 'HSL' is not defined
    __cause__ = None
    __class__ = <class 'NameError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of NameError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of NameError object>
    __doc__ = 'Name not found globally.'
    __eq__ = <method-wrapper '__eq__' of NameError object>
    __format__ = <built-in method __format__ of NameError object>
    __ge__ = <method-wrapper '__ge__' of NameError object>
    __getattribute__ = <method-wrapper '__getattribute__' of NameError object>
    __gt__ = <method-wrapper '__gt__' of NameError object>
    __hash__ = <method-wrapper '__hash__' of NameError object>
    __init__ = <method-wrapper '__init__' of NameError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of NameError object>
    __lt__ = <method-wrapper '__lt__' of NameError object>
    __ne__ = <method-wrapper '__ne__' of NameError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of NameError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of NameError object>
    __repr__ = <method-wrapper '__repr__' of NameError object>
    __setattr__ = <method-wrapper '__setattr__' of NameError object>
    __setstate__ = <built-in method __setstate__ of NameError object>
    __sizeof__ = <built-in method __sizeof__ of NameError object>
    __str__ = <method-wrapper '__str__' of NameError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("name 'HSL' is not defined",)
    name = 'HSL'
    with_traceback = <built-in method with_traceback of NameError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\opt\Kritax64\lib\krita-python-libs\krita\dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 89, in __init__
    self.Settings()
  File "C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 1574, in Settings
    self.Dict_Copy( har_01, self.Set_Read( "EVAL", "har_01", har_01 ) )
  File "C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 1784, in Set_Read
    read = eval( read )
  File "<string>", line 1, in <module>
NameError: name 'HSL' is not defined
```

**Comment by Gnumaru** [comment]
There is no kritarc file (in windows, at least).

I have closed krita, deleted the config folder at "C:\Users\user\AppData\Roaming\krita", downloaded pigment.o from github as a zip file (instead of doing a git clone), started krita (it generated a new krita config folder at AppData\Roaming), unziped pigment.o at "C:\Users\user\AppData\Roaming\krita\pykrita", and uppon restarting krita the error continues the same.

```
NameError
Python 3.10.7: C:\opt\Kritax64\bin\krita.exe
Wed Oct 11 14:13:39 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\opt\Kritax64\lib\krita-python-libs\krita\dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   14         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   15         self.klass = _klass
   16 
   17     def createDockWidget(self):
   18         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'pigment_o.pigment_o_docker.PigmentO_Docker'>

 C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in __init__(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>)
   87         self.Timer()
   88         self.Extension()
   89         self.Settings()
   90         self.Loader()
   91 
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Settings = <bound method PigmentO_Docker.Settings of <pigment_o.pigment_o_docker.PigmentO_Docker object>>

 C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Settings(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>)
 1572 
 1573         # Colors
 1574         self.Dict_Copy( har_01, self.Set_Read( "EVAL", "har_01", har_01 ) )
 1575         self.Dict_Copy( har_02, self.Set_Read( "EVAL", "har_02", har_02 ) )
 1576         self.Dict_Copy( har_03, self.Set_Read( "EVAL", "har_03", har_03 ) )
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Dict_Copy = <bound method PigmentO_Docker.Dict_Copy of <pigment_o.pigment_o_docker.PigmentO_Docker object>>
global har_01 = {'aaa_1': 0, 'aaa_d1': 0, 'active': False, 'ard_1': 0, 'ard_2': 0, 'ard_3': 0, 'cmy_1': 0, 'cmy_2': 0, 'cmy_3': 0, 'cmyk_1': 0, ...}
self.Set_Read = <bound method PigmentO_Docker.Set_Read of <pigment_o.pigment_o_docker.PigmentO_Docker object>>

 C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Set_Read(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>, mode='EVAL', entry='har_01', default={'aaa_1': 0, 'aaa_d1': 0, 'active': False, 'ard_1': 0, 'ard_2': 0, 'ard_3': 0, 'cmy_1': 0, 'cmy_2': 0, 'cmy_3': 0, 'cmyk_1': 0, ...})
 1782             read = setting
 1783             if mode == "EVAL":
 1784                 read = eval( read )
 1785             elif mode == "STR":
 1786                 read = str( read )
read = 'HSL,0,0,0,0,0,0'
builtineval = <built-in function eval>

 C:\opt\Kritax64\<string> in <module>

NameError: name 'HSL' is not defined
    __cause__ = None
    __class__ = <class 'NameError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of NameError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of NameError object>
    __doc__ = 'Name not found globally.'
    __eq__ = <method-wrapper '__eq__' of NameError object>
    __format__ = <built-in method __format__ of NameError object>
    __ge__ = <method-wrapper '__ge__' of NameError object>
    __getattribute__ = <method-wrapper '__getattribute__' of NameError object>
    __gt__ = <method-wrapper '__gt__' of NameError object>
    __hash__ = <method-wrapper '__hash__' of NameError object>
    __init__ = <method-wrapper '__init__' of NameError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of NameError object>
    __lt__ = <method-wrapper '__lt__' of NameError object>
    __ne__ = <method-wrapper '__ne__' of NameError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of NameError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of NameError object>
    __repr__ = <method-wrapper '__repr__' of NameError object>
    __setattr__ = <method-wrapper '__setattr__' of NameError object>
    __setstate__ = <built-in method __setstate__ of NameError object>
    __sizeof__ = <built-in method __sizeof__ of NameError object>
    __str__ = <method-wrapper '__str__' of NameError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("name 'HSL' is not defined",)
    name = 'HSL'
    with_traceback = <built-in method with_traceback of NameError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\opt\Kritax64\lib\krita-python-libs\krita\dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 89, in __init__
    self.Settings()
  File "C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 1574, in Settings
    self.Dict_Copy( har_01, self.Set_Read( "EVAL", "har_01", har_01 ) )
  File "C:\Users\user\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 1784, in Set_Read
    read = eval( read )
  File "<string>", line 1, in <module>
NameError: name 'HSL' is not defined
```

**Comment by EyeOdin** [comment]
The krita manual to find the kritarc file
https://docs.krita.org/en/reference_manual/preferences.html

location:
C:\Users\ _UserName_ \AppData\Local\kritarc
Clean all entries related to Pigmento

**Comment by Gnumaru** [comment]
Indeed, there does exist a "C:\Users\user\AppData\Local\kritarc" file. I just assumed that all krita config files would be inside the "C:\Users\user\AppData\Roaming\krita" directory and didn't search on other places. I'm sorry for the trouble. Now krita starts and loads with pigment.o without trouble =)
