### ISSUE TITLE
It crash the plugin when you change the harmony

### ISSUE THREAD

**Issue by RamonKrita** [EyeOdin/Pigment.O#23]
It happens when i change the harmony from Analogus to complementary. Maybe the photo helps? The fail, makes Krita not usable and the user needs to restart.

![70802d1c80a93683fd5d9e2a94ded995a3f5e4e7](https://github.com/user-attachments/assets/fafeeff7-1e4d-458a-b0d3-eb4799262360)

Now i need to put the text complete here isn't it?

**Comment by RamonKrita** [comment]
Now i am testing in Krita 5.2.6 and i get this

UnboundLocalError
Python 3.10.7: C:\Users\Ramon\Downloads\krita-x64-5.2.6\bin\krita.exe
Sun Nov  3 11:08:47 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\Ramon\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Harmony_Rule(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>, harmony_rule='Triadic')
 5871         self.harmony_rule = harmony_rule
 5872         self.harmony_spread.Set_Rule( self.harmony_rule )
 5873         self.Pigmento_RELEASE()
 5874         Krita.instance().writeSetting( "Pigment.O", "harmony_rule", str( self.harmony_rule ) )
 5875     def Harmony_Edit( self, harmony_edit ):
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Pigmento_RELEASE = <bound method PigmentO_Docker.Pigmento_RELEASE o...gment_o.pigment_o_docker.PigmentO_Docker object>>

 C:\Users\Ramon\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Pigmento_RELEASE(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>)
 4292     def Pigmento_RELEASE( self ):
 4293         self.widget_press = False
 4294         self.Sync_Elements( True, True, True )
 4295 
 4296     #endregion
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Sync_Elements = <bound method PigmentO_Docker.Sync_Elements of <pigment_o.pigment_o_docker.PigmentO_Docker object>>

 C:\Users\Ramon\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Sync_Elements(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>, p2k=True, color_active=True, color_previous=True)
 5015         # Layout
 5016         self.Pigmento_to_Krita( p2k )
 5017         self.Harmony_Header( har_01, har_02, har_03, har_04, har_05 )
 5018         self.Update_Header( color_active, color_previous )
 5019         self.Panels_Set_Value()
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Harmony_Header = <bound method PigmentO_Docker.Harmony_Header of <pigment_o.pigment_o_docker.PigmentO_Docker object>>
global har_01 = {'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}
global har_02 = {'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}
global har_03 = {'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}
global har_04 = {'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}
global har_05 = {'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}

 C:\Users\Ramon\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Harmony_Header(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>, har_01={'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}, har_02={'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}, har_03={'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}, har_04={'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}, har_05={'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...})
 5140     def Harmony_Header( self, har_01, har_02, har_03, har_04, har_05 ):
 5141         # Variables
 5142         self.Color_Harmony( self.harmony_span, har_01, har_02, har_03, har_04, har_05 )
 5143         # Update
 5144         self.Harmony_Update()
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Color_Harmony = <bound method PigmentO_Docker.Color_Harmony of <pigment_o.pigment_o_docker.PigmentO_Docker object>>
self.harmony_span = 0.7302325581395349
har_01 = {'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}
har_02 = {'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}
har_03 = {'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}
har_04 = {'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}
har_05 = {'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}

 C:\Users\Ramon\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Color_Harmony(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>, span=0.7302325581395349, hue_1={'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}, hue_2={'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}, hue_3={'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}, hue_4={'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...}, hue_5={'aaa_1': 0.5685780617028473, 'aaa_d1': 0, 'active': True, 'ard_1': 0.15857605267535324, 'ard_2': 0.5583333436244474, 'ard_3': 0.470638292007904, 'cmy_1': 0.38823527097702026, 'cmy_2': 0.40784311294555675, 'cmy_3': 0.7921568602323532, 'cmyk_1': 0.0, ...})
 4692 
 4693         if self.wheel_mode == "ANALOG":
 4694             angle_1 = self.convert.huea_to_hued( angle_1 )
 4695             angle_2 = self.convert.huea_to_hued( angle_2 )
 4696             angle_3 = self.convert.huea_to_hued( angle_3 )
angle_1 undefined
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.convert = <pigment_o.pigment_o_calculations.Convert object>
self.convert.huea_to_hued = <bound method Convert.huea_to_hued of <pigment_o.pigment_o_calculations.Convert object>>
UnboundLocalError: local variable 'angle_1' referenced before assignment
    __cause__ = None
    __class__ = <class 'UnboundLocalError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of UnboundLocalError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of UnboundLocalError object>
    __doc__ = 'Local name referenced but not bound to a value.'
    __eq__ = <method-wrapper '__eq__' of UnboundLocalError object>
    __format__ = <built-in method __format__ of UnboundLocalError object>
    __ge__ = <method-wrapper '__ge__' of UnboundLocalError object>
    __getattribute__ = <method-wrapper '__getattribute__' of UnboundLocalError object>
    __gt__ = <method-wrapper '__gt__' of UnboundLocalError object>
    __hash__ = <method-wrapper '__hash__' of UnboundLocalError object>
    __init__ = <method-wrapper '__init__' of UnboundLocalError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of UnboundLocalError object>
    __lt__ = <method-wrapper '__lt__' of UnboundLocalError object>
    __ne__ = <method-wrapper '__ne__' of UnboundLocalError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of UnboundLocalError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of UnboundLocalError object>
    __repr__ = <method-wrapper '__repr__' of UnboundLocalError object>
    __setattr__ = <method-wrapper '__setattr__' of UnboundLocalError object>
    __setstate__ = <built-in method __setstate__ of UnboundLocalError object>
    __sizeof__ = <built-in method __sizeof__ of UnboundLocalError object>
    __str__ = <method-wrapper '__str__' of UnboundLocalError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("local variable 'angle_1' referenced before assignment",)
    name = None
    with_traceback = <built-in method with_traceback of UnboundLocalError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\Ramon\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 5873, in Harmony_Rule
    self.Pigmento_RELEASE()
  File "C:\Users\Ramon\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 4294, in Pigmento_RELEASE
    self.Sync_Elements( True, True, True )
  File "C:\Users\Ramon\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 5017, in Sync_Elements
    self.Harmony_Header( har_01, har_02, har_03, har_04, har_05 )
  File "C:\Users\Ramon\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 5142, in Harmony_Header
    self.Color_Harmony( self.harmony_span, har_01, har_02, har_03, har_04, har_05 )
  File "C:\Users\Ramon\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 4694, in Color_Harmony
    angle_1 = self.convert.huea_to_hued( angle_1 )
UnboundLocalError: local variable 'angle_1' referenced before assignment

**Comment by RamonKrita** [comment]
![image](https://github.com/user-attachments/assets/31776055-e390-49f3-8c5f-b86b6ae98d99)
This what i was doing in Krita

**Comment by EyeOdin** [comment]
This error does not seem normal. I am not able to trigger it on my end. I have tripled checked now this section of code on the reported section and all looks sound. conversion is also not breaking in isolation.
[ramon_check.webm](https://github.com/user-attachments/assets/1619446d-98a7-4fa2-86f5-75a4182e0683)

I will require more information to better trigger this or analyze it running on your machine to pin point the issue (it would require boring testing).

**Comment by RamonKrita** [comment]
No problem, after I release the video about templates i will record a video for you . I hope this helps

**Comment by Michaelknubben** [comment]
I also get error popups when I change the harmony settings
Krita 5.2.6
Pigment.O V2.0.0 (according to _init.py, could not find this information in the Python Plugin Manager)
Windows 11 64bit (Version 10.0.22631 Build 22631)

I use 'Docker Under Cursor' to make the Pigment.O docker pop up on hotkey, but it also crashes when I don't trigger it this way.

`UnboundLocalError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Thu Jan 16 13:29:15 2025

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\micha\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Harmony_Rule(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>, harmony_rule='Triadic')
 5871         self.harmony_rule = harmony_rule
 5872         self.harmony_spread.Set_Rule( self.harmony_rule )
 5873         self.Pigmento_RELEASE()
 5874         Krita.instance().writeSetting( "Pigment.O", "harmony_rule", str( self.harmony_rule ) )
 5875     def Harmony_Edit( self, harmony_edit ):
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Pigmento_RELEASE = <bound method PigmentO_Docker.Pigmento_RELEASE o...gment_o.pigment_o_docker.PigmentO_Docker object>>

 C:\Users\micha\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Pigmento_RELEASE(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>)
 4292     def Pigmento_RELEASE( self ):
 4293         self.widget_press = False
 4294         self.Sync_Elements( True, True, True )
 4295 
 4296     #endregion
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Sync_Elements = <bound method PigmentO_Docker.Sync_Elements of <pigment_o.pigment_o_docker.PigmentO_Docker object>>

 C:\Users\micha\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Sync_Elements(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>, p2k=True, color_active=True, color_previous=True)
 5015         # Layout
 5016         self.Pigmento_to_Krita( p2k )
 5017         self.Harmony_Header( har_01, har_02, har_03, har_04, har_05 )
 5018         self.Update_Header( color_active, color_previous )
 5019         self.Panels_Set_Value()
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Harmony_Header = <bound method PigmentO_Docker.Harmony_Header of <pigment_o.pigment_o_docker.PigmentO_Docker object>>
global har_01 = {'aaa_1': 0.6324810306451817, 'aaa_d1': 0, 'active': True, 'ard_1': 0.44038715128766287, 'ard_2': 0.6570695721707286, 'ard_3': 0.5031604110275201, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.2235293984413147, 'cmy_3': 0.4395383121838258, 'cmyk_1': 0.7777777756454568, ...}
global har_02 = {'aaa_1': 0.6455619720102449, 'aaa_d1': 0, 'active': True, 'ard_1': 0.49038715128766286, 'ard_2': 0.6938191296224486, 'ard_3': 0.5635525083688027, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.2235293984413147, 'cmy_3': 0.2583618389835046, 'cmyk_1': 0.7777777756454568, ...}
global har_03 = {'aaa_1': 0.5434116220602951, 'aaa_d1': 0, 'active': True, 'ard_1': 0.5403871512876629, 'ard_2': 0.6721981318667036, 'ard_3': 0.526381941222971, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.36987343109944637, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}
global har_04 = {'aaa_1': 0.4138342084274257, 'aaa_d1': 0, 'active': True, 'ard_1': 0.5903871512876628, 'ard_2': 0.6297151041843471, 'ard_3': 0.4656885253305519, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.5510499042997672, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}
global har_05 = {'aaa_1': 0.2842567947945559, 'aaa_d1': 0, 'active': True, 'ard_1': 0.6403871512876629, 'ard_2': 0.6239425435787479, 'ard_3': 0.40559756427687377, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.7322263775000886, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}

 C:\Users\micha\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Harmony_Header(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>, har_01={'aaa_1': 0.6324810306451817, 'aaa_d1': 0, 'active': True, 'ard_1': 0.44038715128766287, 'ard_2': 0.6570695721707286, 'ard_3': 0.5031604110275201, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.2235293984413147, 'cmy_3': 0.4395383121838258, 'cmyk_1': 0.7777777756454568, ...}, har_02={'aaa_1': 0.6455619720102449, 'aaa_d1': 0, 'active': True, 'ard_1': 0.49038715128766286, 'ard_2': 0.6938191296224486, 'ard_3': 0.5635525083688027, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.2235293984413147, 'cmy_3': 0.2583618389835046, 'cmyk_1': 0.7777777756454568, ...}, har_03={'aaa_1': 0.5434116220602951, 'aaa_d1': 0, 'active': True, 'ard_1': 0.5403871512876629, 'ard_2': 0.6721981318667036, 'ard_3': 0.526381941222971, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.36987343109944637, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}, har_04={'aaa_1': 0.4138342084274257, 'aaa_d1': 0, 'active': True, 'ard_1': 0.5903871512876628, 'ard_2': 0.6297151041843471, 'ard_3': 0.4656885253305519, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.5510499042997672, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}, har_05={'aaa_1': 0.2842567947945559, 'aaa_d1': 0, 'active': True, 'ard_1': 0.6403871512876629, 'ard_2': 0.6239425435787479, 'ard_3': 0.40559756427687377, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.7322263775000886, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...})
 5140     def Harmony_Header( self, har_01, har_02, har_03, har_04, har_05 ):
 5141         # Variables
 5142         self.Color_Harmony( self.harmony_span, har_01, har_02, har_03, har_04, har_05 )
 5143         # Update
 5144         self.Harmony_Update()
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.Color_Harmony = <bound method PigmentO_Docker.Color_Harmony of <pigment_o.pigment_o_docker.PigmentO_Docker object>>
self.harmony_span = 0.2
har_01 = {'aaa_1': 0.6324810306451817, 'aaa_d1': 0, 'active': True, 'ard_1': 0.44038715128766287, 'ard_2': 0.6570695721707286, 'ard_3': 0.5031604110275201, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.2235293984413147, 'cmy_3': 0.4395383121838258, 'cmyk_1': 0.7777777756454568, ...}
har_02 = {'aaa_1': 0.6455619720102449, 'aaa_d1': 0, 'active': True, 'ard_1': 0.49038715128766286, 'ard_2': 0.6938191296224486, 'ard_3': 0.5635525083688027, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.2235293984413147, 'cmy_3': 0.2583618389835046, 'cmyk_1': 0.7777777756454568, ...}
har_03 = {'aaa_1': 0.5434116220602951, 'aaa_d1': 0, 'active': True, 'ard_1': 0.5403871512876629, 'ard_2': 0.6721981318667036, 'ard_3': 0.526381941222971, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.36987343109944637, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}
har_04 = {'aaa_1': 0.4138342084274257, 'aaa_d1': 0, 'active': True, 'ard_1': 0.5903871512876628, 'ard_2': 0.6297151041843471, 'ard_3': 0.4656885253305519, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.5510499042997672, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}
har_05 = {'aaa_1': 0.2842567947945559, 'aaa_d1': 0, 'active': True, 'ard_1': 0.6403871512876629, 'ard_2': 0.6239425435787479, 'ard_3': 0.40559756427687377, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.7322263775000886, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}

 C:\Users\micha\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in Color_Harmony(self=<pigment_o.pigment_o_docker.PigmentO_Docker object>, span=0.2, hue_1={'aaa_1': 0.6324810306451817, 'aaa_d1': 0, 'active': True, 'ard_1': 0.44038715128766287, 'ard_2': 0.6570695721707286, 'ard_3': 0.5031604110275201, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.2235293984413147, 'cmy_3': 0.4395383121838258, 'cmyk_1': 0.7777777756454568, ...}, hue_2={'aaa_1': 0.6455619720102449, 'aaa_d1': 0, 'active': True, 'ard_1': 0.49038715128766286, 'ard_2': 0.6938191296224486, 'ard_3': 0.5635525083688027, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.2235293984413147, 'cmy_3': 0.2583618389835046, 'cmyk_1': 0.7777777756454568, ...}, hue_3={'aaa_1': 0.5434116220602951, 'aaa_d1': 0, 'active': True, 'ard_1': 0.5403871512876629, 'ard_2': 0.6721981318667036, 'ard_3': 0.526381941222971, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.36987343109944637, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}, hue_4={'aaa_1': 0.4138342084274257, 'aaa_d1': 0, 'active': True, 'ard_1': 0.5903871512876628, 'ard_2': 0.6297151041843471, 'ard_3': 0.4656885253305519, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.5510499042997672, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}, hue_5={'aaa_1': 0.2842567947945559, 'aaa_d1': 0, 'active': True, 'ard_1': 0.6403871512876629, 'ard_2': 0.6239425435787479, 'ard_3': 0.40559756427687377, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.7322263775000886, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...})
 4739             if self.harmony_edit == False:
 4740                 # Others
 4741                 if self.harmony_index != 1:self.Color_Convert( mode, angle_1, self.cor[c2], self.cor[c3], 0, har_01 )
 4742                 if self.harmony_index != 2:self.Color_Convert( mode, angle_2, self.cor[c2], self.cor[c3], 0, har_02 )
 4743                 if self.harmony_index != 3:self.Color_Convert( mode, angle_3, self.cor[c2], self.cor[c3], 0, har_03 )
self = <pigment_o.pigment_o_docker.PigmentO_Docker object>
self.harmony_index = 5
self.Color_Convert = <bound method PigmentO_Docker.Color_Convert of <pigment_o.pigment_o_docker.PigmentO_Docker object>>
mode = 'HSV'
angle_1 undefined
self.cor = {'aaa_1': 0.2842567947945559, 'aaa_d1': 0, 'active': True, 'ard_1': 0.6403871512876629, 'ard_2': 0.6239425435787479, 'ard_3': 0.40559756427687377, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.7322263775000886, 'cmy_3': 0.2235293984413147, 'cmyk_1': 0.7777777756454568, ...}
c2 = 'hsv_2'
c3 = 'hsv_3'
global har_01 = {'aaa_1': 0.6324810306451817, 'aaa_d1': 0, 'active': True, 'ard_1': 0.44038715128766287, 'ard_2': 0.6570695721707286, 'ard_3': 0.5031604110275201, 'cmy_1': 0.8274509757757187, 'cmy_2': 0.2235293984413147, 'cmy_3': 0.4395383121838258, 'cmyk_1': 0.7777777756454568, ...}
UnboundLocalError: local variable 'angle_1' referenced before assignment
    __cause__ = None
    __class__ = <class 'UnboundLocalError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of UnboundLocalError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of UnboundLocalError object>
    __doc__ = 'Local name referenced but not bound to a value.'
    __eq__ = <method-wrapper '__eq__' of UnboundLocalError object>
    __format__ = <built-in method __format__ of UnboundLocalError object>
    __ge__ = <method-wrapper '__ge__' of UnboundLocalError object>
    __getattribute__ = <method-wrapper '__getattribute__' of UnboundLocalError object>
    __gt__ = <method-wrapper '__gt__' of UnboundLocalError object>
    __hash__ = <method-wrapper '__hash__' of UnboundLocalError object>
    __init__ = <method-wrapper '__init__' of UnboundLocalError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of UnboundLocalError object>
    __lt__ = <method-wrapper '__lt__' of UnboundLocalError object>
    __ne__ = <method-wrapper '__ne__' of UnboundLocalError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of UnboundLocalError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of UnboundLocalError object>
    __repr__ = <method-wrapper '__repr__' of UnboundLocalError object>
    __setattr__ = <method-wrapper '__setattr__' of UnboundLocalError object>
    __setstate__ = <built-in method __setstate__ of UnboundLocalError object>
    __sizeof__ = <built-in method __sizeof__ of UnboundLocalError object>
    __str__ = <method-wrapper '__str__' of UnboundLocalError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("local variable 'angle_1' referenced before assignment",)
    name = None
    with_traceback = <built-in method with_traceback of UnboundLocalError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\micha\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 5873, in Harmony_Rule
    self.Pigmento_RELEASE()
  File "C:\Users\micha\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 4294, in Pigmento_RELEASE
    self.Sync_Elements( True, True, True )
  File "C:\Users\micha\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 5017, in Sync_Elements
    self.Harmony_Header( har_01, har_02, har_03, har_04, har_05 )
  File "C:\Users\micha\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 5142, in Harmony_Header
    self.Color_Harmony( self.harmony_span, har_01, har_02, har_03, har_04, har_05 )
  File "C:\Users\micha\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 4741, in Color_Harmony
    if self.harmony_index != 1:self.Color_Convert( mode, angle_1, self.cor[c2], self.cor[c3], 0, har_01 )
UnboundLocalError: local variable 'angle_1' referenced before assignment

`

**Comment by Michaelknubben** [comment]
Additional information: I can change between the first three options freely, but Triadic and Tetradic give repeating error popups (and Krita needs to be closed)
