### ISSUE TITLE
Not loading Krita after update to Pigment.O

### ISSUE THREAD

**Issue by okuma10** [EyeOdin/Pigment.O#5]
Hi I get this error
I tried it on the nightly 5.0
and an 4.3.0 version I had around. Both gave me this error

```
AttributeError
Python 3.8.1: G:\Backup\02Krita\build\Stable\bin\krita.exe
Tue Dec  7 22:27:02 2021

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 G:\Backup\02Krita\build\Stable\lib\krita-python-libs\krita\dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
   10         super(DockWidgetFactory, self).__init__(_id, _dockPosition)
   11         self.klass = _klass
   12 
   13     def createDockWidget(self):
   14         return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class 'pigment_o.pigment_o_docker.PigmentODocker'>

 C:\Users\Nikola\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in __init__(self=<pigment_o.pigment_o_docker.PigmentODocker object>)
  316         # Construct
  317         self.Variables()
  318         self.User_Interface()
  319         self.Menu_Shrink()
  320 
self = <pigment_o.pigment_o_docker.PigmentODocker object>
self.User_Interface = <bound method PigmentODocker.User_Interface of <pigment_o.pigment_o_docker.PigmentODocker object>>

 C:\Users\Nikola\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py in User_Interface(self=<pigment_o.pigment_o_docker.PigmentODocker object>)
  493         self.dialog.names_closest.clicked.connect(self.HEX_Closest)
  494         self.dialog.wheel_index.currentTextChanged.connect(self.Menu_Wheel)
  495         self.dialog.wheel_space.currentTextChanged.connect(self.Wheel_Space)
  496         self.dialog.luminosity.currentTextChanged.connect(self.Menu_Luminosity)
  497         self.dialog.release.toggled.connect(self.Menu_Release)
self = <pigment_o.pigment_o_docker.PigmentODocker object>
self.dialog = <pigment_o.pigment_o_modulo.Dialog_UI object>
self.dialog.wheel_space undefined
self.Wheel_Space = <bound method PigmentODocker.Wheel_Space of <pigment_o.pigment_o_docker.PigmentODocker object>>
AttributeError: 'Dialog_UI' object has no attribute 'wheel_space'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'Dialog_UI' object has no attribute 'wheel_space'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "G:\Backup\02Krita\build\Stable\lib\krita-python-libs\krita\dockwidgetfactory.py", line 14, in createDockWidget
    return self.klass()
  File "C:\Users\Nikola\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 318, in __init__
    self.User_Interface()
  File "C:\Users\Nikola\AppData\Roaming\krita\pykrita\pigment_o\pigment_o_docker.py", line 495, in User_Interface
    self.dialog.wheel_space.currentTextChanged.connect(self.Wheel_Space)
AttributeError: 'Dialog_UI' object has no attribute 'wheel_space'

```

**Comment by EyeOdin** [comment]
that sounds like a mistake I did while uploading the new version. try downloading it again to see if it works now.

**Comment by okuma10** [comment]
I just downloaded and reinstalled,
the error is the same, at the same line

**Comment by EyeOdin** [comment]
I am checking the Github files even. "wheel_space" exists in the UI file.
Pigmento is booting up properly on my end. If your updated I am not sure how that is happening. it works on Beta v5.

**Comment by okuma10** [comment]
every time I tried I deleted the pigment.o files and download from the repository the zip.
Not sure why but now I just used the online installer where you give it the github link and now it works.
